name: Build and Run Spring Boot

on:
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17' # Cambia según la versión de Java que uses

    - name: Build and Run
      run: |
        mvn -q -DskipTests spring-boot:run
